### ISSUE TITLE
Decide on Ingress Architecture

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/uds-package-dubbd#29]
For some architectures, we've had admin capabilities be behind a different Istio ingressgateway to provide isolation between admin tools for managing the cluster and tenant applications running on the cluster.  We should make the default decision here to have a single Ingressgateway for all traffic, or split by function.

cc @jeff-mccoy @bburky

**Comment by runyontr** [comment]
Per @blancharda 's request, changing the name from `public`/`private` to a different combo (admin/app, landlord/tenant), and then expose the ability for each of those gateways to use private or public ELBs within AWS

**Comment by austenbryan** [comment]
@bburky @jeff-mccoy @Vandiver247 

We'd like your review on this

**Comment by bburky** [comment]
I believe I was once told separation of admin interfaces is a security requirement from some policy (RMF?). Splitting admin/public interfaces is one way to implement this. It's also nice security hardening that non-admin users cannot even open a network connection to the admin services (because they cannot even reach the admin interface).

A requirement for passthrough TLS (e.g. for client TLS certs to Keycloak) could sometimes drive a requirement for a third gateway. Unless you can do PASSTHROUGH conditionally based on SNI? If PASSTHROUGH works like that, maybe you can keep it on the public interface.
