### ISSUE TITLE
ExternalDNS may not part of an ATO

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-package-dubbd#460]
As a delivery engineer
I want to be able to disable ExternalDNS
Because it's not part of my org's ATO
So that I can deploy DUBBD in prod environments

**Comment by noahpb** [comment]
@UncleGedd is this still needed?

**Comment by UncleGedd** [comment]
Let's follow up with @brianrexrode and @ntwkninja . Noting that the ExternalDNS image does come from IB, but it may not be helpful specifically in the PBME prod env. Did I get that right @brianrexrode / @ntwkninja ?

**Comment by brianrexrode** [comment]
I think my biggest concern would be ensuring `external-dns` is added to our ATO prior to deploying to Prd. Also, as long as `external-dns` is limited to R53 Hosted zones (for adding/updating private admin tool entries not being maintained by other entities) we should be able to use it in Prd clusters.

**Comment by brianrexrode** [comment]
could still be useful to have a `external-dns` *enabled/disabled* option.

**Comment by UncleGedd** [comment]
I thought that because it's an IB image then it would be part of your ATO?

**Comment by brianrexrode** [comment]
I'm pretty sure everything in IB still has to be listed. I can confirm with @Tobyhb

**Comment by brianrexrode** [comment]
Response from Toby:
```
Yep they still want us adding IB images on our ATO's software list and the IB VAT findings documented as eMASS POA&Ms
```

**Comment by UncleGedd** [comment]
Tracking, thanks for the clarification!

**Comment by UncleGedd** [comment]
@noahpb @MxNxPx in light of the above comments, what do you think about adding a config to enable/disable externalDNS?

**Comment by MxNxPx** [comment]
@UncleGedd discussing with the group, we could take a few different approaches:

1. keep external-dns in dubbd-aws, make them optional zarf components instead of `required: true`, and change the `zarf package deploy` command to tack on `--components=external-dns-k8s-manifests,external-dns-chart` when external-dns is required
2. move external-dns out of dubbd and have uds cli orchestrate some way of optionally deploying it before dubbd
3. POTENTIALLY investigate if we have an easier option to toggle with a zarf var if we wrap external-dns in the same way SWF folks do so - https://github.com/defenseunicorns/uds-support-charts

i prefer the uds cli approach (at least long term), but could take a different approach short-term if needed.
